In [3]:
import tensorflow.compat.v1 as tf
a = tf.constant([[1,2],[3,4],[5,6]])
b = tf.constant([[2,4],[1,3]])
c = tf.matmul(a,b)
c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4, 10],
       [10, 24],
       [16, 38]])>

In [4]:
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [5]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [1, 3]])>

In [6]:
d = tf.matmul(c,tf.transpose(c))
d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 116,  280,  444],
       [ 280,  676, 1072],
       [ 444, 1072, 1700]])>

In [7]:
e = tf.einsum('ij,kj->ik',c,c)
e

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 116,  280,  444],
       [ 280,  676, 1072],
       [ 444, 1072, 1700]])>

In [8]:
#https://blog.csdn.net/u013841196/article/details/81140835
t1 = tf.constant([[1,2,3],[2,3,4]])
#t2 = tf.matmul(t1,tf.transpose(t1))
t2 = tf.matmul(t1,t1,transpose_b=True)
t3 = tf.einsum('ij,kj->ik',t1,t1)
t2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [20, 29]])>

In [9]:
t3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 20],
       [20, 29]])>

In [25]:
#https://blog.csdn.net/DBC_121/article/details/109566151
# 在输入数组中重复的字母意味着值沿这些轴相乘
# 输出中省略的字母意味着沿该轴的值将相加
# 我们可以按照我们喜欢的任何顺序返回未没进行累加的轴
# 当处理大量维度时，别忘了einsum允许使用省略号语法’…’。
# 这提供了一种变量的方式标记我们不大感兴趣的轴，例如np.einsum(‘…ij,ji->…’, a, b)，
# 仅将a的最后两个轴与2维数组b相乘
m = tf.constant([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
m1 = tf.matmul(m,m,transpose_b=True)
m2 = tf.einsum('...bc,...fc->...bf',m,m)
m1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[14, 20],
        [20, 29]],

       [[14, 20],
        [20, 29]],

       [[14, 20],
        [20, 29]]])>

In [26]:
m2

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[14, 20],
        [20, 29]],

       [[14, 20],
        [20, 29]],

       [[14, 20],
        [20, 29]]])>

In [29]:
p1 = tf.constant([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
p2 = tf.constant([[[1,2,3]],[[2,3,4]]])
p = tf.einsum('...bc,...fc->...bf',p1,p2)
p

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[14],
        [20]],

       [[20],
        [29]]])>

In [35]:
p1 = tf.constant([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
p2 = tf.constant([[[1],[2]],[[2],[1]]])
p = tf.einsum('...c,...d->...',p1,p2)
p

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6, 18],
       [12,  9]])>